/**
 * This source file was generated by the Gradle 'init' task.
 */
package go.postgres.test;

/**
 * The main application class.
 */
public class App {
    /**
     * Returns a greeting message.
     *
     * @return A string containing the greeting message.
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * The main entry point of the application.
     *
     * @param args Command line arguments.
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
