openapi: 3.0.0
info:
  title: Polyglot Architecture API
  version: 1.0.0
paths:
  /api/v1/resource:
    get:
      summary: Get a resource
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string